### ISSUE TITLE
HTS NN 2.3alpha

### ISSUE THREAD

**Issue by navta** [RasmusD/SiRe#1]
Hi, 

I'm not aware that HTS could support DNN at the moment.
Do you know where I can get this HTS NN 2.3alpha?

Thank you for the great project.

**Comment by RasmusD** [comment]
Hi,

I don't think it has been released yet - I spent time at Nitech under Keiichi Tokuda's supervision while working on SiRe.

I would suggest contacting Kei Hashimoto if you wish to get a hold of the system early - though I suspect it probably will be released fairly soon in some form.

I'm happy to extend SiRe to support any other system if you have a DNN system in mind.
- Rasmus
